# Generated by Django 6.1 on 2026-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
