# Generated by Django 6.0.8 on 2026-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_sourcesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_file',
            field=models.FileField(blank=True, null=True, upload_to='project_demos/'),
        ),
    ]
