# Generated by Django 6.0.8 on 2026-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_demo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_site_url',
            field=models.URLField(blank=True),
        ),
    ]
