# Generated by Django 6.1 on 2026-08-28 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=50)),
                ('readme_cache', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_meta', to='projects.project')),
            ],
        ),
    ]
